// Authentication
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const TOKEN_REFRESH = 'TOKEN_REFRESH'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT = 'LOGOUT'

export const USER_UPDATE = 'USER_UPDATE'

// Quizzes
export const QUIZZES_ERROR = 'QUIZZES_ERROR'
export const QUIZZES_LOADING = 'QUIZZES_LOADING'
export const GET_QUIZZES = 'GET_QUIZZES'
export const GET_QUIZ_SUCCESS = 'GET_QUIZZES_SUCCESS'
export const GET_QUIZ_FAIL = 'GET_QUIZZES_FAIL'
export const CREATE_QUIZ = 'CREATE_QUIZ'
export const CREATE_QUIZ_FAIL = 'CREATE_QUIZ_FAIL'

export const UPDATE_QUIZ_SUCCESS = 'UPDATED_QUIZ_SUCCESS'
export const UPDATE_QUIZ_FAIL = 'UPDATED_QUIZ_FAIL'

export const CATEGORY_SECTION_ERROR = 'CATEGORY_SECTION_ERROR'
export const CATEGORY_SECTION_LOADING = 'CATEGORY_SECTION_LOADING'
export const GET_CATEGORY_SECTION = 'GET_CATEGORY_SECTION'

// Errors
export const ADD_ERROR = 'ADD_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'