# Generated by Django 3.1.4 on 2021-01-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
