# Generated by Django 3.1.4 on 2021-01-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_auto_20210101_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image_url',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2017/01/24/00/21/question-2004314_960_720.jpg'),
        ),
    ]
