# Generated by Django 3.1.5 on 2021-01-29 14:51

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_auto_20210127_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='random_question_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=120, populate_from='question', unique_with=['quiz']),
        ),
    ]
