# Generated by Django 3.1.5 on 2021-01-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_auto_20210129_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
