# Generated by Django 3.1.5 on 2021-01-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_quiz_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='password',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
