# Generated by Django 3.1.5 on 2021-01-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_auto_20210130_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='ask_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='ask_gender',
            field=models.BooleanField(default=False),
        ),
    ]
