# Generated by Django 3.1.5 on 2021-02-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_auto_20210130_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='one_page_questions',
            field=models.BooleanField(default=False),
        ),
    ]
