# Generated by Django 3.1.5 on 2021-02-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_quiz_one_page_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgeanswer',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='knowledgeanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='preferentialanswer',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='preferentialanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='psychologyanswer',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='psychologyanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='psychologyresults',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='universalanswer',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='universalanswer',
            name='question',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question')),
            ],
        ),
        migrations.AlterField(
            model_name='knowledgeanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_answers', to='quizzes.answer'),
        ),
        migrations.AlterField(
            model_name='preferentialanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferential_answers', to='quizzes.answer'),
        ),
        migrations.AlterField(
            model_name='psychologyanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychology_answers', to='quizzes.answer'),
        ),
        migrations.AlterField(
            model_name='universalanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universal_answers', to='quizzes.answer'),
        ),
    ]
