# Generated by Django 3.1.5 on 2021-02-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_auto_20210204_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_times', models.PositiveIntegerField(default=0)),
                ('points', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default='1', max_length=2)),
                ('results', models.ManyToManyField(to='quizzes.PsychologyResults')),
            ],
        ),
        migrations.RemoveField(
            model_name='preferentialanswer',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='psychologyanswer',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='psychologyanswer',
            name='results',
        ),
        migrations.RemoveField(
            model_name='universalanswer',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='KnowledgeAnswer',
        ),
        migrations.DeleteModel(
            name='PreferentialAnswer',
        ),
        migrations.DeleteModel(
            name='PsychologyAnswer',
        ),
        migrations.DeleteModel(
            name='UniversalAnswer',
        ),
    ]
