# Generated by Django 3.1.5 on 2021-02-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0020_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answered_times',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], max_length=2),
        ),
        migrations.AlterField(
            model_name='answer',
            name='results',
            field=models.ManyToManyField(blank=True, to='quizzes.PsychologyResults'),
        ),
    ]
