# Generated by Django 3.1.5 on 2021-02-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_auto_20210204_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answered_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
