# Generated by Django 3.1.5 on 2021-02-05 20:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0022_auto_20210204_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, max_length=120, populate_from='answer', unique_with=['question']),
            preserve_default=False,
        ),
    ]
