# Generated by Django 3.1.5 on 2021-02-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0023_answer_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=80)),
                ('gender', models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman')], max_length=5)),
                ('opinion', models.TextField(blank=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
            ],
        ),
        migrations.DeleteModel(
            name='QuizReview',
        ),
    ]
