# Generated by Django 3.1.5 on 2021-02-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0024_auto_20210207_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='solved_times',
        ),
        migrations.AddField(
            model_name='quiz',
            name='solved',
            field=models.JSONField(default=list),
        ),
    ]
