# Generated by Django 3.1.5 on 2021-02-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0025_auto_20210209_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='solved',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
