# Generated by Django 3.1.5 on 2021-02-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0026_auto_20210209_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='solved',
            new_name='solves',
        ),
    ]
