# Generated by Django 3.1.5 on 2021-02-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0029_auto_20210210_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizPunctaction',
            new_name='QuizPunctation',
        ),
    ]
