# Generated by Django 3.1.5 on 2021-02-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0030_auto_20210210_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='solves',
            new_name='average_correct_answers',
        ),
        migrations.AddField(
            model_name='quiz',
            name='solved_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
