# Generated by Django 3.1.5 on 2021-02-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0031_auto_20210211_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='average_correct_answers',
            new_name='average_correct_answer',
        ),
    ]
