# Generated by Django 3.1.6 on 2021-02-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0033_auto_20210211_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologyresults',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
