# Generated by Django 3.1.6 on 2021-02-24 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0035_auto_20210223_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologyresults',
            name='quiz',
            field=models.ForeignKey(default=535, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quizzes.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='results',
            field=models.ManyToManyField(blank=True, related_name='answers', to='quizzes.PsychologyResults'),
        ),
        migrations.AlterField(
            model_name='psychologyresults',
            name='result',
            field=models.CharField(max_length=100),
        ),
    ]
