# Generated by Django 3.1.6 on 2021-02-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0036_auto_20210224_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologyresults',
            name='image_url',
        ),
    ]
