# Generated by Django 3.1.6 on 2021-03-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0039_auto_20210308_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.CharField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default='0', max_length=2),
        ),
    ]
