# Generated by Django 3.1.6 on 2021-03-12 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0040_auto_20210309_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfeedback',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
