# Generated by Django 3.1.6 on 2021-03-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0041_quizfeedback_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfeedback',
            name='score',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
