# Generated by Django 3.1.7 on 2021-03-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0042_quizfeedback_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='section',
            field=models.CharField(choices=[('Knowledge Quiz', 'knowledge_quiz'), ('Universal Quiz', 'universal_quiz'), ('Psychology Quiz', 'psychology_quiz'), ('Preferential Quiz', 'preferential_quiz')], max_length=17),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
