# Generated by Django 3.1.7 on 2021-03-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0043_auto_20210315_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='section',
            field=models.CharField(choices=[('knowledge_quiz', 'Knowledge Quiz'), ('universal_quiz', 'Universal Quiz'), ('psychology_quiz', 'Psychology Quiz'), ('preferential_quiz', 'Preferential Quiz')], max_length=17),
        ),
    ]
