# Generated by Django 3.1.4 on 2021-01-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_solved_quizzes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
