# Generated by Django 3.1.4 on 2021-01-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210112_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, default='images/DEFAULT_PROFILE_PICTURE.png', upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
